# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Uber_Firebase_clone' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Uber_Firebase_clone

pod 'Firebase'
pod 'Firebase/Database'
pod 'Firebase/Auth'

pod 'RevealingSplashView'

end
